
spring:
  cloud:
    consul:
      discovery:
        fail-fast: true
      host: ${consul_service}
      port: 8500

restapp:
  kafka_service: ${kafka_service_name:kafka}
  kafka_groupid: "restapp-group"